sudo: required
dist: trusty
services: docker
language: generic

notifications:
  email:
    on_failure: always

before_script:
  ./install_linuxcan.sh

env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="indigo" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic" ROS_REPO=ros

matrix:
  allow_failures:
    env: ROS_DISTRO="indigo" ROS_REPO=ros-shadow-fixed
    env: ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed

install:
  git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  source .ci_config/travis.sh
