sudo: required
dist: trusty
language: generic
services:
  - docker
compiler:
  - gcc

notifications:
  email:
    on_failure: always

env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros BEFORE_SCRIPT='./install_minimal_linuxcan.sh' DOCKER_BASE_IMAGE=ros:indigo-ros-core
    - ROS_DISTRO="kinetic" ROS_REPO=ros BEFORE_SCRIPT='./install_minimal_linuxcan.sh' DOCKER_BASE_IMAGE=ros:kinetic-ros-core
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='./install_minimal_linuxcan.sh' DOCKER_BASE_IMAGE=ros:kinetic-ros-core
    - ROS_DISTRO="lunar" ROS_REPO=ros BEFORE_SCRIPT='./install_minimal_linuxcan.sh' DOCKER_BASE_IMAGE=ros:lunar-ros-core
    - ROS_DISTRO="lunar" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='./install_minimal_linuxcan.sh' DOCKER_BASE_IMAGE=ros:lunar-ros-core
    - ROS_DISTRO="melodic" ROS_REPO=ros BEFORE_SCRIPT='./install_minimal_linuxcan.sh' UPSTREAM_WORKSPACE=file DOCKER_BASE_IMAGE=ros:melodic-ros-core
    - ROS_DISTRO="melodic" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='./install_minimal_linuxcan.sh' UPSTREAM_WORKSPACE=file DOCKER_BASE_IMAGE=ros:melodic-ros-core

matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='./install_minimal_linuxcan.sh' DOCKER_BASE_IMAGE=ros:kinetic-ros-core
    - env: ROS_DISTRO="lunar" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='./install_minimal_linuxcan.sh' DOCKER_BASE_IMAGE=ros:lunar-ros-core
    - env: ROS_DISTRO="melodic" ROS_REPO=ros-shadow-fixed BEFORE_SCRIPT='./install_minimal_linuxcan.sh' UPSTREAM_WORKSPACE=file DOCKER_BASE_IMAGE=ros:melodic-ros-core

install:
  git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  source .ci_config/travis.sh
